providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: true

gateway:
  enabled: false

ports:
  ssh:
    port: 2222
    exposedPort: 2222
    protocol: TCP
    expose:
      default: true

service:
  spec:
    type: LoadBalancer
    loadBalancerClass: io.cilium/node
    externalTrafficPolicy: Local
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6
