---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgBVX7CM7l7HRG49ZF9X8jgHygwpSU/rWpWAbT1Kq+5Ykpp5fICjZ+XouwQDSnnhAFYWHZ9YxgbX1LErLRjauOWPhgWVEOANXtLOQ+UvcxTbNsRIJiHnulzgibztAHdri7l55oHB5LjZ0fOGsnqJCVOlOAk7iHf69nnjL+dtFt+uW82ORV7wBuTvhZ5/n0Jn2VbN4PNprktvXOwj+q7RkbIitjOcrwWN2J9c+xRJ8MAT78/NiyTFF3pkVoQOKA01ZjU6JTjFSpXyEpEQafsOeWWO83iyog1dHa0z2owDqV8vpm+vhIQT7zKs5RteC3CGTCHQ9Ldrs5lxGaHlZaojkw0OrzCdGSgdl8J3v02qVrTHbjZBMuH/K30n+vvkE7KCqcYm2QWLSDGQZ3VjAkkbaG0L0atE1MyKlnkGaXBEMmA0zh4YGeHZ8rxx+iLvlZep1DWr87M7OYFZeP8GSHbPoeDoEpRR2lfiNqgOoOMNMbrmb7GUPQCWXGr+Y/JrcYI26CBDlJBFHahE5QHCqowsohsU7k2TwBgvD5YHVmwhs20E8+Ti3uy2jM6sZT3zC4AteJa4T+VMwMvn/Ss+64BfL196vjh/7+vLZhMbtUuHkCD+fh8cpF14L65F2Lh5MO33h7Q+NsOIK0U5TWM4kZ84h8yfzSITmj7cfxQk752vyOcO9wkIYRF9qYXnkwP3r2ufJh6iFI8lBh94/5Kw2lQE1t6VuGntoXI6NB326jKEte0BzPbfcONXn4rLr2huRMFPVrE9apSSNquGToov9DC4c2YhtcI32j86yfCbQNKiE73fEcPF5m8Jh5K+ImubLO/cSc727MXnENL+x9lZWoWZ2fBLDNImjFlalEn0nTTpG3f0rEtni8qtPA==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
