---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgA38AlEOtrqeYTJxci1MdMXSvQjD/vIONpy/D7JmEmFrxM9HgF4okd+KuETVkiW14eR1vI2K0U5YHkGMm9kO4oUMxeaPQFcUz6eMfSyQC3Kdkzo/t8sYb3e/xp58FynzqxHQhQlGYTA8febRPJSLzs73qtJn00C4u1O0yXGI661PraUXRXm9MRi0441HDybb1pU79bc5YVB0yMf84EUyNDd92MLtuml6rq0CtsMREJuS7+Qa0co3FdmzY1g40uXxd9t1wC2KnTX0pLoLGi47h4t2fvBeGDsbIaaqwcohIxEYfM0gDs4S0ytQecuDy6tW15KP3MM0qAAnGnsDrAUSq0PmlGf58VIFM+7tvyJvttwnd6lv37w2FRjmJ2PgGpBCehU4E9qWmXcDFa6NAq/rmsg/GO1vJUsW1FXRc61fJgIDzTwVPJtXsqOju6iQo805nK9g2COqHPmx+dxJSesDDaPJHNQmkhaJ9UmHSdeBKWe2I8+kQEW8aVbtHFUtDBLsQaxpZlba0RHceB0Y+HqJU/Q2XjWKXU0fwtj8c2M2EMwQEsqjhTrT3ggs52CVHeCTTKelymntTEiUawXEyeXLcY1d8wFI2XK8E8fUV3ee0/az7SNVgLYStlSQUs3fL4ELuxqxtsdBYJ9wKTygcNty1FeO0+S5iPDzkrWRoX9MgGa1ajh4CMcnNyn6kEZz5LK32riBG17CB3TgvJuQE0DBM+ErOyfjUJIvxe6Lkrp
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
