signupsAllowed: false

domain: "https://warden.salami.network"

adminToken:
  existingSecret: "vaultwarden-admin-token"
  existingSecretKey: "token"

database:
  type: postgresql
  existingSecret: "vaultwarden-db-app"
  existingSecretKey: "uri"
