renovate:
  existingSecret: "renovate-secret"
  renovate:
    config: |
      {
        "platform": "github",
        "autodiscover": false,
        "gitAuthor": "Renovate Bot <renovate@salami.network>",
        "repositories": [
          "fulsiram/homelab"
        ]
      }
