global:
  domain: argocd.salami.network

configs:
  params:
    server.insecure: true

server:
  httproute:
    enabled: true
    parentRefs:
      - name: gateway
        namespace: gateway-infra
        sectionName: https-wildcard

  grpcroute:
    enabled: false
    parentRefs:
      - name: gateway
        namespace: gateway-infra
        sectionName: https-wildcard
