---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-conf
  namespace: akaia-peering
spec:
  encryptedData:
    wg0.conf: AgAvfd6GazTVd8Q0dP6MxaB+NN6b/nKsOmm5YkvLtvzpCktER/J11tTD+6IQhMDB5cfmScTTBosBAMd6D5j0sffzvp9v7+jPo1mVVNSHkwm1Wh3nLF9dNUF042YKfGy6fUBxRhnjxNA9PWfQeR/sFLDUireUHCh2b5JbA0zTKmPAGcE5hvLAfMcnZBle0BnNgPAbVC7vWFQ+FxBWMwa9Tx++hPdPT261xf0fo8SzjtFVxsCkrAzYgEElpM9sy8goH1Ioyz/PXyPZ8nRNiTeqpWZLTBYfFx+0OZXDovlKY8jdVOycTWewYdPwnosR73r//IaDm00zc70jaSIotTK7g0d7dQQIa4sLE9pi4qcI3l3TCtCSL0gpFj0bSRIswxQfRDCy8CqA7FDyDxHIKwDO53L6kaO3VENYn4em6YOweWALCjohm0CetGAnSju0SewqU39G11tf7nK/VNjRnsulnSh29+FyyyVTOp+lBsWL7x9kJ3HZ9w99RbxopQ7m1r9ypXY9AgW3HKdDQsWl0z3PFo6d17JISdw2c65EiIej/lnL2KQTh7tau9VE7jNX3Oj4/je40iQgIhd0BX2yDM6WRiFaNlerL3gP2G40DtZNQJfc5XTflchCLcgvKWHQ6YUtQutspxb+mcuZuMcB6VqQ6R1NIWBfgi7wfdIXClPbSujhvT1s5JwpKYTzBFL2GTwUj9rcUURhRzswaH4GOsYJz8I3BncwkTJ0198ZdpN4gmg2d6pQyjBREpyC7pcJP48Ha1r2IhJUafShMa00wIjAmgIRwFKOPXrs1Wo9BP031paKRac/cE43mkHjSMfd6Gb7UBTaAPPcfqEa0p6jVmCRXYYsWdlQS9S5YO/dOMmZr2Y3bKuENezXL0Ax4cw1EVHDL7VNCofKLNhjjinf5l2is+14aZg5D2XnoKmJ2D6Dx0spnGQ5ikQk7ws5OgbalnGUkJGZYiT9XZitAbM8OGZaM5ZOfC5p5O0MCSUryARCE0yh7cR/WAzvmpsKjrVYa10tUCugu6Ug6IS2vfk/or2w+hudwWVkz8Ehd29vXCjDaDcGAe1jhVnjSk1kFheycCO85VJhmlRX4N/ujjZ0ghqyWqVHfTRiXLnLQ+MFtsPCZ39Mq2X1/97F4y1ThMQUhNasjjja6qXEGRitHJzg7/AUCRJH2pspSN+8aY0FPDKJxHD78gD496ZUBdNDrO0iBnjDyHvlTaMcfcE=
  template:
    metadata:
      name: wireguard-conf
      namespace: akaia-peering
