apiVersion: v1
kind: Service
metadata:
  name: wireguard
  labels:
    app.kubernetes.io/name: wireguard
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/node
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    app.kubernetes.io/name: wireguard
  ports:
    - name: wg
      port: 51830
      targetPort: wg
      protocol: UDP
