global:
  domain: argocd.salami.network

configs:
  cm:
    application.resourceTrackingMethod: annotation
    resource.exclusions: |
      - apiGroups:
        - "*"
        kinds:
        - ProviderConfigUsage
    kustomize.buildOptions: --enable-helm
  params:
    server.insecure: true

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  httproute:
    enabled: true
    hostnames:
      - argocd.salami.network
    parentRefs:
      - name: gateway
        namespace: gateway-infra
        sectionName: https-wildcard

  grpcroute:
    enabled: false
    parentRefs:
      - name: gateway
        namespace: gateway-infra
        sectionName: https-wildcard

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
