---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBfOzh9FXa+T49n28jTXF4N3KfERk5JcJVG7zl3x8xRWhiyomw4xnMOIw4Ox5WjbsQeruaI0M07/Fv1Q2XdDbl2/3K6hQQjBpsOv7/53VmykCIX6yma2QheyOK/soq7hNWCOy5cPPx7QEgh+p5oIXsFbA/dPGESBz3LLr9f6h6pqOvZ/wfODY1L0bUwT6aOGQ/rJG0+DSYIZhe2zZbWDtYqtqrsXvxI2TjRv4ShQBW1rz+kgVRJ5WnTU73kfgjZ9foO3cBFjlYSm6Tllgzvpe5htAIdS0A1a/KgRqr2MbMUfJ9Jf9K7/II1HJCjJmBu7kkMOkTNyljTRtA6gBQ8zs55XJemLGqH7IOBVcQOq+wYsJQ6YQLR/GShVFck2EYrmjc7JHUbsr6GWzFHCaUd5aBK5vWuhDVeYt14/yoM5kHGgLYj53OSjoNQJiHhSg1ocNoevDnKhi+YtjdykSXkEkVsqkxy6Rp3b/Z97Qxl0O2fToBGsOYybgQ2XVRpYY0vD1qWCDPALJq0jn9dp/ZpR2bJOxVffk/j+7WRgqZUIj3BOSJg2IYwAIGVvGCNeEqzt4Hi98b7UPR+1a27J7wUtzFsc+cNRzGlzisrzPmz4BzxL4hv6xXLPX00ZP76arzIhF9raCstpl4ZUekt/Ul6HGfKfIdq7LyyeOfdr+sqEOoej7Nm2q3lUj6I/fbugiSpfzLfiRCg1+kVEZFFjq6neXcDlCxXC9I2CK6anPCjtoHam2bw69f144FYwqtWoq3frbNac+lijroXmMdR+J5S9d9R3icQpa57zImlx7x6szP81hyMKGrBLIgVzDguUVB5ZnACa+xymKtfeZ5BEPdOa/BZ+Vu4TeNZ1ycd/nw23mO2BPMqXHi7WIxjjw9jbEXFGyEmztaVX7qYyjkaPsk=
  template:
    metadata:
      name: warpgate-creds
      namespace: crossplane-system
