apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-yggdrasil
spec:
  package: harbor.salami.network/images/function-yggdrasil:latest
  packagePullSecrets:
    - name: harbor-creds
