apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.2.1
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/kubernetes/apps/crossplane/values.yaml
    - repoURL: https://github.com/fulsiram/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-packages
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/homelab.git
      path: kubernetes/crossplane/providers/
      targetRevision: main
    - repoURL: https://github.com/fulsiram/homelab.git
      path: kubernetes/crossplane/functions/
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-xrds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fulsiram/homelab.git
    path: kubernetes/crossplane/apis/
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
