apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-desec-webhook
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/platform-lab.git
      path: kubernetes/apps/acme-desec-webhook
      targetRevision: main
      helm:
        releaseName: desec-webhook
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
