apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fulsiram/platform-lab.git
    path: kubernetes/apps/generic-device-plugin/app/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
