apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fulsiram/homelab.git
    path: kubernetes/apps/keycloak/app/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fulsiram/homelab.git
    path: kubernetes/apps/keycloak/db/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
