apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      path: .
      targetRevision: 86.0.1
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/kubernetes/apps/kube-prometheus-stack/app/values.yaml
    - repoURL: https://github.com/fulsiram/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/fulsiram/homelab.git
      targetRevision: main
      path: kubernetes/apps/kube-prometheus-stack/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
