# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-ovn
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     - repoURL: oci://ghcr.io/kubeovn/charts/kube-ovn-v2
#       path: .
#       targetRevision: v1.16.2
#       helm:
#         releaseName: kube-ovn
#         valueFiles:
#           - $values/kubernetes/apps/kube-ovn/config/values.yaml
#     - repoURL: https://github.com/fulsiram/platform-lab.git
#       targetRevision: main
#       ref: values
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kube-system
#   syncPolicy:
#     automated:
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
