apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus-cni
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/platform-lab.git
      path: kubernetes/apps/multus-cni/app/
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: multus-cni
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
