apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/platform-lab.git
      path: kubernetes/apps/tekton/app/
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-config
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/platform-lab.git
      path: kubernetes/apps/tekton/config/
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-ci-pipelines
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/platform-lab.git
      path: kubernetes/pipelines/nixos-dev-images/
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-pipelines
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
