apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-db
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/fulsiram/platform-lab.git
      path: kubernetes/apps/vaultwarden/db/
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
