---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: desec-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBR9lzWU9F9FD5m89tAExNoB0sxq4NIIWzrkofWSYp7AdgMJcsm0o2InesN2YNuQeX1skwkFHZwOnXzUkV64BkImnl6gqE0EeKHaWvxkcDdf6F0tnXnxXU2/a7GTq1lPf7ggdw74v5+ij00R9FXBFTUqf/h1hDKVwfRrLq+lng9P3b15VzGVAFKd7eSe1/eTsoKgXP5U2OjG2ajs75bx6wtYcPTQb4EuI5xA792p32ZBZ7UxsjFPlmnoctSUndn5j4I4Uln14P54C6blySLhldS6zGkT2wsPwX4pUaCHjXAcAgZpA00iZsK0t13Lg1JEcRD4PH+knEqV/xNIBmV+nnxARTwmY+zDsMfgO/EMuUD01w5ENRIdViY80wjlNKPryzD3x/DNi1SHAOMKNwh2OH994KBUO7pynytsaV6PSI9GWaE1RQlwVR1snJe2Pq7c/OMLqCqU5kbcrXoLgNvrXFpXrs87Mkisgz9qv95LqNAWPosUATE6wec0WhOpVp3t+PglZ2rV4n2c2jYdADRLp+Cihvbdcug0grtlzoYMC7jzpL6fCiZcIW1z4DUwKura7NdiSPBswLoE/MSZYHqtV7g/6L1mEApUv7I31baNgYj5KyfkACvB1YErafaQPo87jQssjbf0LXuBDEStgUz6WOOYvKVqXgz5Qbgqe7rlOI9zddBD8TmMulLUTgFyUjSdETr33JMhQtCAPFSQt6FLOb+outFBEzIbWD3jqG/
  template:
    metadata:
      name: desec-api-token
      namespace: cert-manager
