---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-desec-token
  namespace: external-dns
spec:
  encryptedData:
    token: AgBvlAIdbGaEilX8NKqLOZfpwscok9obRVDa8cMt+pHaNLMeegHNaCEuloHOeSkLxixgdQ3+ad3It1RAOdvKyll6opLrWv2GGh3GGK7Kpdx3dFAifL2v5+/xd8DlRC90YyBDKTwpV79yUZZRBK1SsX1lLEeJS+2Y1ZWYaYv3bsP44K9gbMCQ51oHU52BWIUOguoa8rt0ljmcTO9tmsy+KP1c0zwmjkZ8nQkA5iTOwgxhy7c2b38EFehi4wbWafv4tPdb/eXAPcAYCGJy40/TMNyobB7+k4ngy9HREdSr5DcgXLUPWcgGgvBLlnwTQvCEK7jLFsO0cf6j/5Uy+TEYocb7eiVXpJ3XB6AsfzBvVe2Ukv/WjGig3MD35DSSeXpPtxW2ZNTy5QFARGEr9GIRhTFaqtMA9vFTafYHECVeO4Y9gENXas68/bmU8/NFgxdQ/sD0H0aZXndgEmILxrpS/HA7avsdEnBZK1zD7KIKn+dINtR20WnIyqde7jgBMBFUe2oHJMirXIcT0rzM/sEYo9dW/Gz80d9yU98GUz/XAVBci7NxF0ZPxCou12f4CtRGSJuR9bM9hJO9xqS5XQAV3N1/EpGviwNPuYV1fZD7wINSzNab2mR+LGZ0wl/C7xjfBa8FpUJpLDa2/9F4ekYyvt6QJx5o9N4zjGw9q3HbSGO0g0WDwyvScbEp6cEZMUkFZ0lHP91yvv9WBvWlEEmB8PHXxzL7/xI+A8aHVa8O
  template:
    metadata:
      name: external-dns-desec-token
      namespace: external-dns
