---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-creds
  namespace: external-dns
spec:
  encryptedData:
    .dockerconfigjson: AgC9Al/3QL0kBoNsYRRuYol8kCmsedye+GT8Aey5dl58cQ5NFTADYm20QCKjPUSwSAqduAk9vAPiyyRFuK519nGkS6nt9k8wdKflpyuW8qzHKB0oNVmM9LN48ZbPcyhIY/t3ORVWCkfIQdMTMGavm2iOJfxLoE9OqrlzHewvhA2KR9FqNfrpR/3LeD8jGcaFSt7WAXJzjCge1E6oJPrNE+yiE/t9mio2Pr4Iy1Mv61YtaoQjTX2LCUGHgmYAG4I1NUXrAAXYPj97ClLu+djwEn/TLC647byFSqnWYF8wYa/ZewncnmXZi+7H69biJwCgWZwM2DDx7D7eNN0YDKkMhm2ZwttkanjxNdgJi983Bnn9FabtCqmVOOPiylvVCfOBVmJa1XVbTCQDTBj6TzQRzRnCCHsqq4Mpmfpj1+0IVLIrQssGzGg1cJaZQyomRvKtZ5SWo51rVHnPv8S7/pwuat0kU5e3lsDHqarL9Y9eT09P3jJsEIlSy55Xhrt8aGPV0uhn3tmceYexRG/3IxpEqLW5VTzoefXnnyWjinI194VEhCA+W29zyB6LGzuIaUmtWxW11nhBPAS2+hNxWL7TmnhN4QGtqq8HBuViJd+VJi3FZVZpYx1kURd/phhCa5RqPttBrrKdPEbYqRLzdHGqDvfgcniqsgke4SoPEO9AprEdAu/1o1OEuJFQegUMT3o0nVr8NaDm/JoR9T0a9jWA8C9TmZHYoL0+6YeOQBQo6IjBh3unYBDIw+9j8lZl7OinMsjPn8Mq1v1bLd5IUwVvozfwOktSFv6CDMwg4jWz45uedSBtf8Hft7bA/yV8nV/PX8WbfuYjt0XcEmPVbwTyuA5+LbIv2ps4AJ/Af9uAH/M8Q7J9fuB9Ddgong+ydAM+pjBHQpxNjxvWm7f9HTZn1LWkk+fTS/TMzC/q7DZ5BMFnSXAHbh0H7IfrCRm03kh8ZVgZFgBmy266
  template:
    metadata:
      name: harbor-creds
      namespace: external-dns
    type: kubernetes.io/dockerconfigjson
