---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-secret
  namespace: warpgate
spec:
  encryptedData:
    adminPassword: AgAJFWLSu942UwtzYT2yd8ucldIvH4r4YdC5+XDGwUD9r/7WNPzjnBhPVSADQFKlJ58NDgPQwjen7Cd0Uk7PF90KV7uTZQweQWqdXspYgcyBUtw5H6pc1l3aKguvp4M36Af09nIXVgacjw0dm0PRhhnNYLHyfxavLxzibjKH/86H+R91uRcuIocIVC5rLL3MuQ59mxsFxFhzhiH/rzoswXxpn8zT7Ubot+sq4gBawVT1DUAzluVlqZB7XH/jfnr1HM3q2NWPXHap/aFrg0Z37KuGaAsmrBOKebvMdba4SV6ETV//JgKWTSg+UUYyPKcWREO4JU+k0UTqXWBfwvyfk8Y/kJw3WLZGimOZ6qqZ/OmeAtmfl2neGkfTXze0YwL6b3DN61DHtosrnjIxCBAjjytsHTwjToS23+rizgudR5bCCiA8gTMKvqgzs5RkTin/+YurHCOj1eGYOygq26+CS52TxXQeeNPxwcGb17JdsHKht3vAwD/x4FC/qNesVlS0JN6zhbk2KootJzC13mzLoLCPVq4hw86IdsWHBaWIc0sEgrSPJoH3wBvf34iFKkhrLBQuhjZziaDQhdKAKbnMymLhO8FYx1ipAqujpRPiEc/znvoPNr9ELxq9UrApvZpL1dWnY1Xo32PSrHjq2PGSt8RUGXrsDBMqNLQTfmsT4G9974rqSJO+sAB4AODx/1c3Pc8=
  template:
    metadata:
      name: warpgate-secret
      namespace: warpgate
