---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgALSTSo4l3QcsWzhDZ4ThwsMM0Q6kqJ0F7uKGThwlF8KLzVWiBmJQVoL6stXCq8RnYyAc4lqboi12cUtuO/czQtHWYd/3OTwttlwc19VNGQW5vuW+oiDTimGtO/007CmYmIs0p6Ww6BiFSJ/793d6QGYtwjYY2EZS51XqDsw+Jp2/XMLDCf5jB9EUv8BigYSWZLNehX4DJiPOOeA/bGjM8mzWJWUOwBmo6PoWJ4F5GE9so6sCYVO3gMV+X2TS422/nMhVYTadhCv0Lrl4bGNI65xtEvHElM/a4uwcRw9nGecApxlSA1RGXil0GsyyLiQxQUZ4+xFP95vgwzeyZ9CIHo4glOTCBiOSF67UdmuwbhgeJCXDnGuh44lKx1wuWWY3DqFL1GdGkQYh9CUwyh3TMiVAALcGC6+zMG2vJgm6mBbKPVyLQnZguiMjdnhbFMrGO5cG8uUeU/thjhI++HuvbyvGpZ3j0Fk/YA6AJLcpVu33mcwGL0B/BGtraG7pqCh9ze0474ZlzNr4jEoLKGs948wZXxFsF1N7rsJABmHBkWxY5Swrwt/1gt8plul9rmDaHUnrtsviTVe97toK5zm96zWMwMOnWfEb5cv5A8QLseXWkvhRhmTMDSeXtyw9i7uSqjdEawhCEx33IKpZ+RBcrJp44FqaThwjtwM3AmszkubIJwPukk+sY56zaWlBMRw1AvrRdagE4VdHaFYlsc/H3t8+h7puhT+/otcfbEYEy8Nz7mpKTcvuw6ttGDbBid7AP3rsAU+9WIvmg4y455PbCaZi7ELiJsfRwCXXav8dPmnc3S4y9sLt27oqr7Lgs=
  template:
    metadata:
      name: renovate-secret
      namespace: renovate
