apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfspv-block
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
parameters:
  poolname: "zroot/zcrypted/openebs/pv1"

---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: zfspv-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: zfs.csi.openebs.io
deletionPolicy: Delete
