---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-secret
  namespace: warpgate
spec:
  encryptedData:
    adminPassword: AgAK3NgSij3/Q1QOhjLizgaUGjNSdYKE48MuSOojYrT1KwJgn+bvMw9zlgj0spQLgLrlzLOTPmE+qJCXGRw5SukTlYzakvzeZ8e17snkjdUFK4cmmQWanF7Ygk6kR6edKp7Q4LKfqMO99KBBmxyPL3+0iX3OdkaxvPe18FR8sHnvEOzpkAb65HyHBgn0eeiD+Bi1yX/xR65W1XiUh0PxRdaWvZBDIeyHlzhIDJ8x8J6V3/99jBnpIo4UJaZpB4tW+J4wYJAarVc9PYs1/MrCf17raBFTD0JCS7asN+3cZzeybrM7n6x3K8Y7JRM14dzJ7lBkn2VrtmtRQjQCGSxm+9vI/N/TTmo5nqx3OFZvjLkGefto8nq8XiPNXxRDJmzK9k/IVsFew6qFh9E4D3y1Os9P8zOvx2H2chan4AGHETgQeAfI51z1FRbReUdmYYY5EtHZUGGQ/CFweTnbfFuZ0MRzDeWj9qImWpXb/Gc1kP3rxVnvGVb/kbr2D4lIsVTYlGL4XmbfzWcYZqg6BCTa0MWdmDx4Mr/3qlybyiPt/XxT3i+4xmO2nMSvLv3Cyv3YxmZbuxB3A3BJi+an9kl7Sb0EO1VpDYYW6Is42BvrJf/b3/6kX34GgklzMYuad/2yUf0GD6h8dx5Pfyy+vVtF4yWFDQAR5GaRopgCkQYDf0pEBBD9Ew8l8eJAQ0Wao0ZT0V+z/dj3X+7M8B78z849pSWifZyBzmUOSBWGVbt+WBvKGA==
  template:
    metadata:
      name: warpgate-secret
      namespace: warpgate
