---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warpgate-sso
  namespace: warpgate
spec:
  encryptedData:
    clientId: AgA5UD20RVRBz0gBu9kzrqOc6XVBBI4FEodslUkYDtfpgtvv6eUWStKltEVg6uE27QlckU8CY0pFzjkZTQsAA2zdfmLphtqJqBANV1kVLmbs8jrhU8JxxrTCFfczrVoKMG9DREmIGppDEdfnmsAj845b9A/ZlSftcPauvuxEJ0WQPemGGLlsfPBaSjkE/nDt19hqwpX3vv6H2fDUEVH6LTFMH+D3P8qZW4KQJAwhEgzt2Ha4Pd5Uhf7ECgt16v5RFwtphk6q8C8VrA5bGHoK4z47j7EUQn995HDtqtRrHcIqwO7kDo4VF7uC/Qzh+OlNTbjfHvUEiyMH3Bezetwkxo9M8aJgmH0kMAjxCkygkBodX5jXe69ttXODm22bT4AR91mA1PcKW+bpsUEUphxIiYFhro2j9YnQDjyV+FUWvlrlngnwCUIIlG3v24nGglG6RPMppFfwPn60JBlL38doKoGll4EULsxHrUQ9zx3uGapiQA4UMzDfrQa8enOlxxmPWsCDKHkAEWSZ1BERScxjvVU/BjwzYrJm78/iScrHGq1L/prWr+GGyyVr2xbZaiUXXe9ATWbHayIaIhfOKJUIaMnYHnNn7xa6MfhOMftJxtz4rVZfweqwma80iYSW8O3njbksrBCi3kIyXqsFqjcvHbZ5mUpViT5uSPNvi1k5cnEANiRvDQ1xHYUffJVaD1JQJZvJRhiL97E1yw==
    clientSecret: AgB4b0SEPAIXIL5OaW4dyWTCVtljmyEAkQRHRAJSFjRzZEkxAL6yOKo5WaZeu2QDo564xBDLh6yVo2NxrfQty/xdQDffNcFmjkrS1sNgDbFjBL58jINiu6CIif8LpzMMMMxkP8czzh8KXEOjZSbotA99+ay8u18tTYxL4Sg01NQ77aTuqAxtxMJNbHj1wspx2j2S0cVerAF4HUlQW2a/DKZ1AoXkPsUksfNHbUppUinBMCcCuL2Vwjmc0msbGCWaaQAqpCOCUNnISmSeAUwfTc3Z3m5Z0EbfLDVcvBQePcc9atpizWE644yXIKUpPQOUGBrEClvgbsl6RoequhVnjiSjztAwaajxTwHJHhMYokRikf/1QWprbWmKPd2R8oZNQ/5MdhEPbRd14jyEo+SFJ31EmgIBFl43mydxR/XWPlIFcbbe7ySkYpFGu4+/CzbInnt2ya2JLU3b4sOglU4veLdmr0GF9zsIyvV3sEltDyefIuJSnC3i/oguV4m7aQVY6IgeEo4DwyqG1U6zPqwsEdW/Uayx9nrS5SKd0aNVlJLFwxaLSo6dPSVZm+nUmhQNqQ+yma5VZErdXic6/rjSX9MrodbbrkpDF34OReozf9iw1JRfNNZYQ1bjJlK8eFN2HRrFuo8o8Du6D1AvHLAO1XOOOerZdSD5MeJ0RvWi8OYbuypc4gMZ6Bn39XjqxVQV1UgLLwFnDhpOxZJ2hg2dQPA8boJ+KONIIyIUwhzIZcrnFQ==
  template:
    metadata:
      name: warpgate-sso
      namespace: warpgate
