args:
  - start

http:
  relativePath: /

proxy:
  enabled: true
  mode: xforwarded
  http:
    enabled: true

database:
  vendor: postgres
  hostname: keycloak-db-rw
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: keycloak-db-app
  existingSecretKey: password

extraEnv: |
  - name: KC_HOSTNAME
    value: https://auth.salami.network
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:MaxRAMPercentage=50.0
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

httpRoute:
  enabled: true
  parentRefs:
    - name: gateway
      sectionName: https-wildcard
      namespace: gateway-infra
  hostnames:
    - auth.salami.network
