expose:
  type: route
  tls:
    enabled: true
    certSource: none
  route:
    parentRefs:
      - name: gateway
        sectionName: https-wildcard
        namespace: gateway-infra
    hosts:
      - harbor.salami.network

externalURL: https://harbor.salami.network
