expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.salami.network
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    controller: default
  tls:
    enabled: true

externalURL: https://harbor.salami.network
