expose:
  type: route
  route:
    parentRefs:
      - name: gateway
        sectionName: wildcard-salami-network
        namespace: gateway-infra
    hosts:
      - harbor.salami.network

externalURL: https://harbor.salami.network
