apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt:aggregate-to-crossplane
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - "virtualmachines"
      - "virtualmachineinstances"
    verbs:
      - "*"
  - apiGroups:
      - cdi.kubevirt.io
    resources:
      - "datavolumes"
    verbs:
      - "*"
  - apiGroups:
      - target.warpgate.m.salami.network
    resources:
      - "targets"
      - "targets/status"
    verbs:
      - "*"
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs: ["*"]
