apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: devboxes.platform.salami.network
spec:
  scope: Namespaced
  group: platform.salami.network
  names:
    kind: Devbox
    plural: devboxes
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                exposedPorts:
                  type: array
                  items:
                    type: integer
                owner:
                  type: string
              required:
                - owner
            status:
              type: object
              properties:
                address:
                  type: string
                yggdrasilAddress:
                  type: string
                yggdrasilPubkey:
                  type: string
      additionalPrinterColumns:
        - name: Address
          type: string
          jsonPath: .status.address
        - name: Owner
          type: string
          jsonPath: .spec.owner
