---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    client-id: AgCkvYUK7jV5XDnbz+ul0jPsvq/dNIaziJtSfN+ZHf6eHz51GGaq/VEgmcEMY4WSLG24MTuD3WJVu5bWgFhn0Rjfl02URZeUAl6KzUP8rfG3hlIGe1JuTB7B+KU+lrS0PlkUzDv9sNPMp3PEJoVQXO0jttAXStTn83i1MacJ4m0WW7i5dVD+x9lDdYxzn4LgG4l1K/U8xNO8b0dCH0Een6c2TCWbqTAfiH7oZ2rsDobjz+oQZ/iaQIlQwGeQcyph9sJ6g/fYQAjEFCvhJYSftU3ynSmceGnljh5ErkUbSxce8zYf96itE62DPgnsJE0boib5tGv/fn6dNNXR4o5NyuB8E7PH+Osq+utDrOp5KqmSF8G5VlhU4EZgymhcskVjh6TN0CABMeu+28BpAvn8jehZ8giOCquMarj0fme66uVs2W3y9Cfm1NK59d8Bebey4FbUXjqot9drB+8vv/Um/H4OzqmNaEoZ4ISHXhlS3mY/XrBJKCuiiwmeLQvh5C0AZUrv8RDbko7L3c9L1ZfFP9ibPz7ARnj/JT+VmILvOpvA3v9cBD9cq9KdnaQY5HTS+7HLHr2A3YZR99TnV80bB82abWfeMWaWIgOO/5uMCVJGm/btzfrAZXdAApkQb0AUAXeF9yEqub8ODkQEbrFjTZkrXtQGpWavjtUnP/npO5pOWf/LVlqU4lMsHAQZuG+JJ2uh3oYo6d29
    client-secret: AgCeVqIGK/Tw1ggL7QcccHtrcu/DTGd/6BG3Y5EzxFm4gca/b7TCF667fn39RFsi6WNYrzHOmKM5IuadKPJaMc0B4vneHtrOPu67Kx8AQ3fNODcfcDeFvFoCiYp7moIBb6W7i4HD3Qaowh6ezLSEJy6lQpvCqcq93VxwnVnPasQJWgAhtlSBdNmY+soPuSZXttiP6qEju9bT7AZDbNUf+PHVFKxijFjkAlHfBO7M1VLMaFhDd6XEqhz8A/QsN++OWPu/nqimG7OeI+yaiS9dRA3NavpX1QbWJ2OzitYWDfbJ9OGwcEWnoVFwZ1J5/4b0GI425ir9DWyZX/o2cJdgVuOxATcUKS8N5+D0S5F9Qf4+e+dXZRz1ms5oKFQ0OQ1e8x1F97GcCE6F8tPmk+GDRRNLN6+5n+sOhDVe8xo7KPKO5XoIM5DbXJC9Q3hMNC12JDbYACNgbzu1tMgvncw1meeyMhCJ1OZokDlm9L9MaMyzoiHUMdokqKmYyDiU1cQSvrJm4RIBhqkJ3ISY0CiYSuQsHXI+lDhTpnIPkvrrcYDyGIxCZqhAyHXW8P42sfta9l7UKwedbdk2+el/cA1JhwvV9k+Vgnbb9sWgjf+Ligmz6NvQ4yGdUvN6fwag5mPQXWwI2xrImkrHwlR0bFeQ+JxIBslnJPX2Vw01ONHj0LN4FdckK0hE/i0djKO7WgCDO2ao0hANw7Frx1mcEoUB1hYllxMnt5HvyRkWzXE8b0Vtsg==
  template:
    metadata:
      name: grafana-oauth
      namespace: monitoring
